{\rtf1\ansi\deff0\deftab720{\fonttbl{\f0\fmodern Courier New;}}
{\colortbl\red0\green0\blue0;\red255\green255\blue255;\red200\green200\blue200;\red0\green0\blue0;\red160\green160\blue160;\red190\green190\blue230;\red128\green128\blue255;\red0\green128\blue128;\red128\green0\blue0;\red240\green0\blue240;\red240\green200\blue240;\red0\green0\blue160;\red135\green135\blue200;\red0\green160\blue0;\red154\green200\blue154;\red190\green0\blue190;\red190\green137\blue190;\red0\green0\blue255;\red190\green190\blue255;\red224\green160\blue0;\red224\green206\blue159;\red132\green160\blue132;\red255\green0\blue0;\red255\green200\blue200;\red128\green255\blue255;\red64\green64\blue128;\red133\green133\blue172;}
{\info{\comment Generated by the Code::Blocks RTF Exporter plugin}
{\title Untitled}}

\deflang1033\pard\plain\f0\fs16 \cb3\cf13 #include <iostream>
\par #include <cstdlib>
\par 
\par \cb3\cf11\b using namespace \b0\cb3\cf13\b std\b0\cb3\cf22 ;
\par \cb3\cf4 /*
\par     W ponizszym programie punkty zgromadzone w tablicy przesun o zadany Wektor.
\par     Program testujacy zostal napisany, zawiera jednak blad, ktĂłry nalezy poprawic.
\par     Nastepnie "zdejmujac" komentarze nalezy stopniowo uzupelniac program o brakujace elementy,
\par     ktore pozwola na skompilowanie i uruchomienie programu.
\par     W programie dodatkowo:
\par     - zadbaj o to ĹĽeby wspolrzedne wektora AB byly podawane przez uzytkownika.
\par     - tablica dynamiczna punktow byla uzupelniana roznymi wartosciami
\par */
\par 
\par \cb3\cf11\b class \b0\cb1\cf0 Wektor\cb3\cf22 \{
\par \cb3\cf11\b friend class \b0\cb1\cf0 Punkt\cb3\cf22 ;
\par \cb3\cf11\b private\b0\cb3\cf22 :
\par     \cb3\cf11\b double \b0\cb1\cf0 x\cb3\cf22 ;
\par     \cb3\cf11\b double \b0\cb1\cf0 y\cb3\cf22 ;
\par \cb3\cf11\b public\b0\cb3\cf22 :
\par     \cb1\cf0 Wektor\cb3\cf22 (\cb3\cf11\b double\b0\cb3\cf22 , \cb3\cf11\b double\b0\cb3\cf22 );
\par     \cb3\cf11\b void \b0\cb1\cf0 wypisz\cb3\cf22 () \cb3\cf11\b const\b0\cb3\cf22 ;
\par \};
\par 
\par \cb3\cf11\b class \b0\cb1\cf0 Punkt
\par \cb3\cf22 \{
\par \cb3\cf11\b private\b0\cb3\cf22 :
\par     \cb3\cf11\b double \b0\cb1\cf0 x\cb3\cf22 ;
\par     \cb3\cf11\b double \b0\cb1\cf0 y\cb3\cf22 ;
\par \cb3\cf11\b public\b0\cb3\cf22 :
\par     \cb1\cf0 Punkt \cb3\cf22 (\cb3\cf11\b double\b0\cb3\cf22 ,\cb3\cf11\b double\b0\cb3\cf22 );
\par     \cb1\cf0 Punkt\cb3\cf22 ();
\par     ~\cb1\cf0 Punkt\cb3\cf22 ();
\par     \cb3\cf11\b void \b0\cb1\cf0 wypisz\cb3\cf22 () \cb3\cf11\b const\b0\cb3\cf22 ;
\par     \cb3\cf11\b void \b0\cb1\cf0 przesun_o_wektor\cb3\cf22 (\cb3\cf11\b const \b0\cb1\cf0 Wektor\cb3\cf22 &);
\par \};
\par 
\par \cb3\cf11\b void \b0\cb1\cf0 Punkt\cb3\cf22 ::\cb1\cf0 przesun_o_wektor\cb3\cf22 (\cb3\cf11\b const \b0\cb1\cf0 Wektor\cb3\cf22 & \cb1\cf0 w\cb3\cf22 )\{
\par     \cb1\cf0 x \cb3\cf22 += \cb1\cf0 w\cb3\cf22 .\cb1\cf0 x\cb3\cf22 ;
\par     \cb1\cf0 y \cb3\cf22 += \cb1\cf0 w\cb3\cf22 .\cb1\cf0 y\cb3\cf22 ;
\par \}
\par 
\par \cb3\cf11\b int \b0\cb1\cf0 main\cb3\cf22 ()
\par \{
\par     \cb3\cf13\b cout\b0\cb3\cf22 <<\cb3\cf17 "Podaj liczbe punktow "\cb3\cf22 ;
\par     \cb3\cf11\b int \b0\cb1\cf0 n\cb3\cf22 ;
\par     \cb3\cf13\b cin\b0\cb3\cf22 >>\cb1\cf0 n\cb3\cf22 ;
\par     \cb3\cf11\b if \b0\cb3\cf22 (\cb1\cf0 n\cb3\cf22 >\cb3\cf9 0\cb3\cf22 )
\par     \{
\par         \cb1\cf0 Wektor AB\cb3\cf22 =\{\cb3\cf11\b static_cast\b0\cb3\cf22 <\cb3\cf11\b double\b0\cb3\cf22 >(\cb1\cf0 rand\cb3\cf22 ()%\cb3\cf9 12\cb3\cf22 ),\cb3\cf11\b static_cast\b0\cb3\cf22 <\cb3\cf11\b double\b0\cb3\cf22 >(\cb1\cf0 rand\cb3\cf22 ()%\cb3\cf9 5\cb3\cf22 )\};
\par 
\par         \cb1\cf0 Punkt \cb3\cf22 *\cb1\cf0 wsk\cb3\cf22 =\cb3\cf11\b new \b0\cb1\cf0 Punkt\cb3\cf22 [\cb1\cf0 n\cb3\cf22 ];
\par         \cb3\cf11\b for\b0\cb3\cf22 (\cb3\cf11\b int \b0\cb1\cf0 i\cb3\cf22 =\cb3\cf9 0\cb3\cf22 ; \cb1\cf0 i\cb3\cf22 <\cb1\cf0 n\cb3\cf22 ; ++\cb1\cf0 i\cb3\cf22 )
\par         \{
\par             \cb3\cf13\b cout\b0\cb3\cf22 <<\cb3\cf17 "\\n-----------------------------------------\\n"\cb3\cf22 ;
\par             \cb3\cf13\b cout\b0\cb3\cf22 <<\cb1\cf0 i\cb3\cf22 +\cb3\cf9 1\cb3\cf22 <<\cb3\cf17 ".\\nPunkt "\cb3\cf22 ;
\par             \cb1\cf0 wsk\cb3\cf22 [\cb1\cf0 i\cb3\cf22 ].\cb1\cf0 wypisz\cb3\cf22 ();
\par         \}
\par 
\par         \cb3\cf13\b cout\b0\cb3\cf22 <<\cb3\cf17 "Przesuniecie punktow o wektor "\cb3\cf22 ;
\par         \cb1\cf0 AB\cb3\cf22 .\cb1\cf0 wypisz\cb3\cf22 ();
\par 
\par         \cb3\cf11\b for\b0\cb3\cf22 (\cb3\cf11\b int \b0\cb1\cf0 i\cb3\cf22 =\cb3\cf9 0\cb3\cf22 ; \cb1\cf0 i\cb3\cf22 <\cb1\cf0 n\cb3\cf22 ; ++\cb1\cf0 i\cb3\cf22 )
\par         \{
\par             \cb1\cf0 wsk\cb3\cf22 [\cb1\cf0 i\cb3\cf22 ].\cb1\cf0 przesun_o_wektor\cb3\cf22 (\cb1\cf0 AB\cb3\cf22 );
\par             \cb3\cf13\b cout\b0\cb3\cf22 <<\cb3\cf17 "\\n-----------------------------------------\\n"\cb3\cf22 ;
\par             \cb3\cf13\b cout\b0\cb3\cf22 <<\cb1\cf0 i\cb3\cf22 +\cb3\cf9 1\cb3\cf22 <<\cb3\cf17 ".\\nPunkt "\cb3\cf22 ;
\par             \cb1\cf0 wsk\cb3\cf22 [\cb1\cf0 i\cb3\cf22 ].\cb1\cf0 wypisz\cb3\cf22 ();
\par         \}
\par 
\par 
\par         \cb3\cf13\b cout\b0\cb3\cf22 <<\cb3\cf17 "\\n-----------------------------------------\\n"\cb3\cf22 ;
\par         \cb3\cf11\b delete \b0\cb3\cf22 []\cb1\cf0 wsk\cb3\cf22 ;
\par         \cb1\cf0 wsk\cb3\cf22 =\cb3\cf11\b nullptr\b0\cb3\cf22 ;
\par     \}
\par     \cb3\cf13\b cout\b0\cb3\cf22 <<\cb3\cf17 "\\n-----------------------------------------\\n"\cb3\cf22 ;
\par     \cb3\cf13\b cout\b0\cb3\cf22 <<\cb3\cf17 "\\nKoniec programu\\n"\cb3\cf22 ;
\par     \cb3\cf13\b cout\b0\cb3\cf22 <<\cb3\cf17 "\\n-----------------------------------------\\n"\cb3\cf22 ;
\par     \cb3\cf11\b return \b0\cb3\cf9 0\cb3\cf22 ;
\par \}
\par 
\par \cb3\cf5 //defincje metod klasy Punkt
\par 
\par \cb1\cf0 Punkt\cb3\cf22 ::\cb1\cf0 Punkt\cb3\cf22 (\cb3\cf11\b double \b0\cb1\cf0 xx\cb3\cf22 ,\cb3\cf11\b double \b0\cb1\cf0 yy\cb3\cf22 )
\par \{
\par     \cb3\cf11\b this\b0\cb3\cf22 ->\cb1\cf0 x\cb3\cf22 =\cb1\cf0 xx\cb3\cf22 ;
\par     \cb3\cf11\b this\b0\cb3\cf22 ->\cb1\cf0 y\cb3\cf22 =\cb1\cf0 yy\cb3\cf22 ;
\par \}
\par 
\par \cb1\cf0 Punkt\cb3\cf22 ::\cb1\cf0 Punkt\cb3\cf22 ()\{
\par     \cb1\cf0 x \cb3\cf22 = \cb1\cf0 rand\cb3\cf22 ()%\cb3\cf9 20 \cb3\cf22 - \cb3\cf9 10\cb3\cf22 ;
\par     \cb1\cf0 y \cb3\cf22 = \cb1\cf0 rand\cb3\cf22 ()%\cb3\cf9 20 \cb3\cf22 - \cb3\cf9 10\cb3\cf22 ;
\par \}
\par 
\par \cb1\cf0 Punkt\cb3\cf22 ::~\cb1\cf0 Punkt\cb3\cf22 ()
\par \{
\par     \cb3\cf13\b cout\b0\cb3\cf22 <<\cb3\cf17 "\\nDestruktor punktu "\cb3\cf22 ;
\par     \cb3\cf11\b this\b0\cb3\cf22 ->\cb1\cf0 wypisz\cb3\cf22 ();
\par \}
\par 
\par \cb3\cf11\b void \b0\cb1\cf0 Punkt\cb3\cf22 ::\cb1\cf0 wypisz\cb3\cf22 () \cb3\cf11\b const
\par \b0\cb3\cf22 \{
\par     \cb3\cf13\b cout\b0\cb3\cf22 <<\cb3\cf17 "("\cb3\cf22 <<\cb3\cf11\b this\b0\cb3\cf22 ->\cb1\cf0 x\cb3\cf22 <<\cb3\cf17 ", "\cb3\cf22 <<\cb3\cf11\b this\b0\cb3\cf22 ->\cb1\cf0 y\cb3\cf22 <<\cb3\cf17 ")"\cb3\cf22 ;
\par \}
\par 
\par \cb1\cf0 Wektor\cb3\cf22 ::\cb1\cf0 Wektor\cb3\cf22 (\cb3\cf11\b double \b0\cb1\cf0 xx\cb3\cf22 ,\cb3\cf11\b double \b0\cb1\cf0 yy\cb3\cf22 )
\par \{
\par     \cb3\cf11\b this\b0\cb3\cf22 ->\cb1\cf0 x\cb3\cf22 =\cb1\cf0 xx\cb3\cf22 ;
\par     \cb3\cf11\b this\b0\cb3\cf22 ->\cb1\cf0 y\cb3\cf22 =\cb1\cf0 yy\cb3\cf22 ;
\par \}
\par 
\par \cb3\cf11\b void \b0\cb1\cf0 Wektor\cb3\cf22 ::\cb1\cf0 wypisz\cb3\cf22 () \cb3\cf11\b const
\par \b0\cb3\cf22 \{
\par     \cb3\cf13\b cout\b0\cb3\cf22 <<\cb3\cf17 "("\cb3\cf22 <<\cb3\cf11\b this\b0\cb3\cf22 ->\cb1\cf0 x\cb3\cf22 <<\cb3\cf17 ", "\cb3\cf22 <<\cb3\cf11\b this\b0\cb3\cf22 ->\cb1\cf0 y\cb3\cf22 <<\cb3\cf17 ")"\cb3\cf22 ;
\par \}
\par 
\par \cb3\cf5 //definicje metod klasy Wektor
\par }